---

- name: Network Agnostic Playbook
  hosts: ~^arista
  gather_facts: no

  vars:
    dnsserver: "8.8.8.8"

  tasks:
    - name: CONFIGURE DNS
      cli_config:
        config: ip name-server {{ dnsserver }}

    - name: CHECK CONFIGURATION
      cli_command:
        command: show run | i ip name-server
      register: _results

    - name: PRINT OUTPUT TO THE SCREEN
      debug:
        var: _results.stdout
