---

- name: Network Agnostic Playbook
  hosts: ~^arista
  gather_facts: no

  tasks:
    - name: CONFIGURE DNS
      cli_config:
        config: ip name-server 8.8.8.8

    - name: CHECK CONFIGURATION
      cli_command:
        command: show run | i ip name-server
      register: _results

    - name: PRINT OUTPUT TO THE SCREEN
      debug:
        var: _results.stdout
