---

- name: Push a script and run it
  hosts: localhost

  tasks:
    - script: /home/student/mycode/pyhello02.py
      args:
        executable: python3
        creates: /home/student/mycode/stopper.txt
      register: _results

    - debug:
        msg: "{{ _results }}"
