---

- name: A few basic filters
  hosts: localhost
  gather_facts: False

  vars:
    jarlist: [1,1,1,1,1,5]
    repeatlist: [1,2,2,4,4,4,4,9,9,9,9]
    repeat2list: [5,5,5,5,5,6,7]
    complexlist: [6,7,8,[9,10,22],87]

  tasks:
    - name: The min filter
      debug:
        msg: "Show me the lowest number in the list: '{{ jarlist|min }}'"

    - name: The max filter
      debug:
        msg: "Show me the largest number in the list: '{{ jarlist|max }}'"

    - name: flatten a list
      debug:
        msg: "The list was complext '{{ complexlist }}' but now it is not '{{ complexlist|flatten }}'"

    - name: flatten a list and loop
      debug:
        msg: "We just want to use the items from the list {{ item }}"
      loop: "{{ complexlist|flatten }}"

    - name: Drop any items that repeat to produce a unique set
      debug:
        msg: 'We just want the unique set from a list {{ repeatlist|unique }}'

    - name: produce a union list from the two lists
      debug:
        msg: "Display the union of the lists {{ repeatlist|union(repeat2list) }}"

    - name: show the diffs between the lists
      debug:
        msg: "Display the diffs of the two lists {{ repeatlist|difference(repeat2list) }}"
