---

- name: Another network playbook example
  hosts: ~^arista
  gather_facts: no

  tasks:
    - name: Harvest Arista facts
      eos_facts:
      when: ansible_network_os == 'eos'

    - name: Push to the local system
      copy:
        content: " {{ ansible_facts | to_nice_json }}"
        dest: "/home/student/mycode/{{ inventory_hostname }}.txt"
      tags:
        - never
        - grabfacts

    - name: Getting at the network interfaces
      debug:
        var: "{{ ansible_facts.net_interfaces | length }}"

    - fail:
        msg: "FAIL. Network device lacks the correct number of interfaces."
      when: ansible_facts.net_interfaces | length != 14

    - fail:
        msg: "FAIL. Network device is running the wrong firmware."
      when: "'4.22.0F' not in ansible_facts.net_version"
