---

- name: A Play to play with python
  hosts: localhost

  vars:
    test_list:
      - '192.168.2.1'
      - '10.10.0.2'
      - 'host.example.org'
      - '192.168.70.0/24'
      - 'fe80::100/10'
      - True
      - 'Witcher3 The Wild Hunt'
      - 'Earl Grey Tea, hot'
    mytest_string: "ncc1701 uss enterprise"
    myaddresses: ['192.168.2.101', '10.0.3.50', '171.172.32.1']

  tasks:
    - name: I just want the IPs
      debug:
        msg: "{{ test_list | ipaddr }}"

    - name: spawn random MAC
      debug:
        msg: "{{'52:54:00' | random_mac }}"

    - name: Some don't require mustache brackets
      debug:
        var: "'52:54:11'|random_mac"

    - name: Test if our string ends in a prise
      debug:
        msg: "{{ mytest_string.endswith('prise') }}"

    - name: This only prints when this tests true using python
      debug:
        msg: "Ahh, but is it the Enterprise A, B, C or D?"
      when: mytest_string.endswith('prise')

    - name: Using jinja2 to capitalize a string
      debug:
        #msg: "{{ mytest_string | capitalize }}"
        msg: "{{ mytest_string | upper }}"

    - name: The python method of capitalization
      debug:
        #msg: "{{ mytest_string.capitalize() }}"
        msg: "{{ mytest_string.upper() }}"

    - name: Pop the number 50 on the screen
      debug:
        msg: "{{ (myaddresses|ipaddr('10.0.0.0/8'))[0].split('.')[3] }}"
